# Generated by Django 5.0 on 2024-03-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='WeatherApi_table',
        ),
    ]
