# Generated by Django 5.0 on 2024-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField()),
            ],
        ),
    ]
