# Generated by Django 5.0 on 2024-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0004_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField()),
                ('stars', models.IntegerField(max_length=5)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'User_FeedBack_Form',
            },
        ),
    ]
