# Generated by Django 5.0 on 2024-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0005_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('temperatue', models.FloatField(max_length=50)),
                ('humidity', models.FloatField(max_length=50)),
                ('wind', models.FloatField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
            ],
        ),
    ]
