# Generated by Django 5.0 on 2024-04-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0006_saveuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='saveuser',
            table='Weather_Description',
        ),
    ]
